### ISSUE TITLE
Is there a NuGet package for this available?

### ISSUE THREAD

**Issue by matthid** [FakeBuild/Xake#28]
What I found is https://www.nuget.org/packages/Xake/1.0.3-alpha5 Is there more or is everything part of this package?
I would like to add this to the fake documentation as an alternative to the targets-syntax. Is this something you would be interested in?
Have you ever tried to use this in combination with the fake 5 runner?

**Comment by matthid** [comment]
Oh I didn't realize you are already on it (briefly mentioned in https://github.com/fsharp/FAKE/issues/1888).
Feel free to send PRs to fake docs if you are ready :)

**Comment by OlegZee** [comment]
@matthid, I would be glad this project to be part of FAKE 5 and currently working on migration everything to netcore. What do you think if we give it a different name, such as Fake.Recipes or Fake.Scripts?

Have you look over the [docs](https://github.com/OlegZee/Xake/wiki)? There're a bunch of cool features such as incremental builds, estimate time prediction and progress indicator. It's similar to google's [Bezel](https://bazel.build/) and originally it was an attempt to copycat [Shake](https://shakebuild.com/).

It currently works with FAKE5 and I just pushed the [netcore-bootstrap](https://github.com/OlegZee/Xake/blob/feature/netcore/samples/build.fsx) example.

**Comment by matthid** [comment]
Ok to give you a rough roadmap: After the fake 5 release the next logical step would be to extract some modules into their own repository. Therefore it doesn't make a lot of sense to make something (that is already living on it's own) part of the fake repository now until we are at some later stage.

From a users perspective it doesn't make a lot of difference where the code lives as the integration is easy (just add the module). Like I said - I welcome update to the docs (which should make it seamless and not noticeable to users where the actual code lives).

If you want to rename your project because of this integration that would be up to you but not required from my point of view. (though it would obviously match the fake naming scheme)

**Comment by OlegZee** [comment]
@matthid, thanks, good!

**Comment by matthid** [comment]
To reword/clarify a bit (edited some errors above): It doesn't make a lot of sense to add stuff which already is perfectly split into it's own repository. But if the integration Fake-Xake happens to break in the future I'm perfectly open to adding it to the fake repository.

I guess for now we would have something like a new "folder" in the modules menu:
- Modules
  - Build DSL
     - Fake.Core.Target
     - Xake

Closing this for now as I feel like we have similar ideas going forward. Looking forward to this :)

**Comment by OlegZee** [comment]
@matthid I completed migration to netcore/FAKE 5, extracted .NET specific tasks to a separate assembly, updated docs and so on.

Could you please add a module reference to FAKE 5 docs and RT https://twitter.com/olegzeee/status/996801367514677248?

**Comment by matthid** [comment]
Maybe [Like this](https://github.com/fsharp/FAKE/pull/1927/commits/aff95e5268d88780d0de108f90ebe927a8efedcf)? Feel free to send updates - I have no idea how to integrate as we currently kind of used the "module-category" (basically the namespace). I'm open for ideas :)

**Comment by OlegZee** [comment]
@matthid that is fine now, thank you very much!
